Bugfix - Fix preview page caused by exception due null reference.
Error message:

```python
  File "mwiki/src/mwiki/login.py", line 136, in wrapper
    response = http_handler(*args, **kwargs)
  File "mwiki/src/mwiki/server.py", line 664, in route_preview
    builder = render.HtmlRenderer(base_path=BASE_PATH, preview = True)
  File "mwiki/src/mwiki/render.py", line 516, in __init__
    self._timestemap = int(100000 * self._page_path.lstat().st_mtime)
                                    ^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'lstat'
````

Solution: Use Pyhthon's ternary operation if-else statement
that is evaluated as an expression.

```python
  self._timestemap = int(100000 * self._page_path.lstat().st_mtime) \
                                if self._page_path is not None else 0
```