Bugfix - Fix command $ mwiki export exception ValueError ... must be only a file name.
Issue: The function   get_path_to_resource_file(module, resource_file)
does not accept relative file path, such as /static/somefile.txt, instead
it only accepts file names  such as 'somefile.txt'.

Solution: Change the implementation of this function to
call get_path_to_resouce_file. It works with mwiki installed
using UV tool or docker. However, this function may not
work if mwiki is deployed as PEX zip archive. Therefore,
the function may require future change if the deployment
method is changed.

Steps to reproduce this bug:

(1) Install this tool using UV

```sh
$ cd mwiki-project-directory
$ uv tool install .
````

(2) Run the command mwiki export to export the whole wiki to a static website.

```sh
$ mwiki export --wikipath=./sample-wiki  \
                                                 --website-name=MBook \
                                                 --main-font=cmu-concrete \
                                                 --title-font=chicago \
                                                 --code-font=libertinus-mono \
                                                 --output=./out --latex-renderer=katex --author="John Doe" --source
... ... ... ... ... ... ... ... ... ... .... ...

Traceback (most recent call last):
  File "/home/caesar/.local/bin/mwiki", line 10, in <module>
    sys.exit(main())
  File "/home/caesar/Documents/projects/mwiki/src/mwiki/cli.py", line 366, in main
    cli()
  File "/home/caesar/.local/share/uv/tools/mwiki/lib/python3.10/site-packages/click/core.py", line 1462, in __call__
    return self.main(*args, **kwargs)
  File "/home/caesar/.local/share/uv/tools/mwiki/lib/python3.10/site-packages/click/core.py", line 1383, in main
    rv = self.invoke(ctx)
  File "/home/caesar/.local/share/uv/tools/mwiki/lib/python3.10/site-packages/click/core.py", line 1850, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/caesar/.local/share/uv/tools/mwiki/lib/python3.10/site-packages/click/core.py", line 1246, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/caesar/.local/share/uv/tools/mwiki/lib/python3.10/site-packages/click/core.py", line 814, in invoke
    return callback(*args, **kwargs)
  File "/home/caesar/Documents/projects/mwiki/src/mwiki/cli.py", line 305, in export
    mwiki.export.export(  wikipath, output, page, website_name
  File "/home/caesar/Documents/projects/mwiki/src/mwiki/export.py", line 114, in export
    static_html_renderer = make_template_renderer(mwiki, "templates/static.html")
  File "/home/caesar/Documents/projects/mwiki/src/mwiki/export.py", line 289, in make_template_renderer
    template  = utils.read_resource(module, template_file)
  File "/home/caesar/Documents/projects/mwiki/src/mwiki/utils.py", line 255, in read_resource
    with importlib.resources.open_text(module, resource_file) as fd:
  File "/home/caesar/.local/share/uv/python/cpython-3.10.16-linux-x86_64-gnu/lib/python3.10/importlib/resources.py", line 82, in open_text
    open_binary(package, resource), encoding=encoding, errors=errors
  File "/home/caesar/.local/share/uv/python/cpython-3.10.16-linux-x86_64-gnu/lib/python3.10/importlib/resources.py", line 42, in open_binary
    resource = _common.normalize_path(resource)
  File "/home/caesar/.local/share/uv/python/cpython-3.10.16-linux-x86_64-gnu/lib/python3.10/importlib/_common.py", line 34, in normalize_path
    raise ValueError(f'{path!r} must be only a file name')
ValueError: 'templates/static.html' must be only a file name
```